version: '3.5'
services:
  openwrt-packages-build:
    image: "openwrtorg/sdk:x86_64-21.02.1"
    container_name: openwrt-packages-build
    volumes:
     - ./bin:/home/build/openwrt/bin
     - ./key-build:/home/build/openwrt/key-build
     - ./build.sh:/home/build/openwrt/build.sh
    command: "./build.sh"